const images = {
    // header
    logo: require('../assets/Header/logo.png'),
    story: require('../assets/Header/story.png'),
    story2: require('../assets/Header/story-2.png'),
    question: require('../assets/Header/question.png'),
    question2: require('../assets/Header/question-2.png'),
    good: require('../assets/Header/good.png'),
    good2: require('../assets/Header/good-2.png'),
    prod: require('../assets/Header/prod.png'),
    prod2: require('../assets/Header/prod-2.png'),
    us: require('../assets/Header/us.png'),
    us2: require('../assets/Header/us-2.png'),
    pressed: require('../assets/Header/pressed-r.png'), 
    pressedL: require('../assets/Header/pressed-l.png'), 


    hBG: require('../assets/home/set/bg/1.png'),
    hBG1: require('../assets/home/set/bg/1-1.png'),
    hBG2: require('../assets/home/set/bg/2.png'),
    hBG3: require('../assets/home/set/bg/3-1.png'),
    hBG4: require('../assets/home/set/bg/3.png'),
    hBG5: require('../assets/home/set/bg/4.png'),
    harea: require('../assets/home/set/story.png'),
    hpic1: require('../assets/home/set/story-1.png'),
    hpic2: require('../assets/home/set/story-2.png'),
    hpic3: require('../assets/home/set/story-3.png'),
    hb1: require('../assets//home/Banner1.jpg'),
    hb2: require('../assets//home/Banner2.jpg'),
    hfarm1: require('../assets/home/farm-1.jpg'),
    hfarm2: require('../assets/home/farm-2.jpg'),
    hfarm3: require('../assets/home/farm-3.png'),
    hmap: require('../assets/home/map.jpg'),
    hsh1: require('../assets/home/sh-1.jpg'),
    hsh2: require('../assets/home/sh-2.jpg'),
    hsh3: require('../assets/home/sh-3.jpg'),
    hsun: require('../assets/home/sun.png'),
    htitle: require('../assets/home/title.png'),
    hto: require('../assets/home/tomato.jpg'),
    hline: require('../assets/home/line.png'),

    footer: require('../assets/footer.png'),
};

export default images;