const images = {
    // header
    logo: require('../assets/Header/logo.png'),
    story: require('../assets/Header/story.png'),
    story2: require('../assets/Header/story-2.png'),
    question: require('../assets/Header/question.png'),
    question2: require('../assets/Header/question-2.png'),
    good: require('../assets/Header/good.png'),
    good2: require('../assets/Header/good-2.png'),
    prod: require('../assets/Header/prod.png'),
    prod2: require('../assets/Header/prod-2.png'),
    us: require('../assets/Header/us.png'),
    us2: require('../assets/Header/us-2.png'),
    pressed: require('../assets/Header/pressed-r.png'),
    pressedL: require('../assets/Header/pressed-l.png'),


    hBG: require('../assets/home/set/bg/1.png'),
    hBG1: require('../assets/home/set/bg/1-1.png'),
    hBG2: require('../assets/home/set/bg/2.png'),
    hBG3: require('../assets/home/set/bg/3-1.png'),
    hBG4: require('../assets/home/set/bg/3.png'),
    hBG5: require('../assets/home/set/bg/4.png'),
    harea: require('../assets/home/set/story.png'),
    hpic1: require('../assets/home/set/story-1.png'),
    hpic2: require('../assets/home/set/story-2.png'),
    hpic3: require('../assets/home/set/story-3.png'),
    hb1: require('../assets//home/Banner1.jpg'),
    hb2: require('../assets//home/Banner2.jpg'),
    hfarm1: require('../assets/home/farm-1.jpg'),
    hfarm2: require('../assets/home/farm-2.jpg'),
    hfarm3: require('../assets/home/farm-3.png'),
    hmap: require('../assets/home/map.jpg'),
    hsh1: require('../assets/home/sh-1.jpg'),
    hsh2: require('../assets/home/sh-2.jpg'),
    hsh3: require('../assets/home/sh-3.jpg'),
    hsun: require('../assets/home/sun.png'),
    htitle: require('../assets/home/title.png'),
    hto: require('../assets/home/tomato.jpg'),
    hline: require('../assets/home/line.png'),

    color1: require('../assets/story/combin/color block/color1.png'),
    color2: require('../assets/story/combin/color block/color2.png'),
    titleBg: require('../assets/story/titleBg.png'),
    workSpace1: require('../assets/story/workSpace1.png'),
    hello: require('../assets/story/hello.png'),
    bors: require('../assets/story/3bor.png'),
    bor1: require('../assets/story/combin/bro1.png'),
    bor2: require('../assets/story/combin/bro2.png'),
    bor3: require('../assets/story/combin/bro3.png'),
    pic1: require('../assets/story/pic1.png'),
    pic2: require('../assets/story/pic2.png'),
    titleBg: require('../assets/story/titleBg.png'),
    special1: require('../assets/story/combin/special-1.png'),
    special2: require('../assets/story/combin/special-2.png'),
    special3: require('../assets/story/combin/special-3.png'),
    special4: require('../assets/story/combin/special-4.png'),
    titleBg: require('../assets/story/titleBg.png'),
    paint: require('../assets/story/paint.png'),
    tips: require('../assets/story/tips.png'),
    month: require('../assets/story/month.jpg'),
    month1: require('../assets/story/month-1.jpg'),
    month2: require('../assets/story/month-2.jpg'),
    month3: require('../assets/story/month-3.JPG'),
    month4: require('../assets/story/month-4.JPG'),
    month5: require('../assets/story/month-5.JPG'),
    month6: require('../assets/story/month-6.JPG'),
    month6: require('../assets/story/month-6.JPG'),
    search: require('../assets/status/search.png'),
    statusBg: require('../assets/status/color1.png'),

    footer: require('../assets/footer.png'),
};

export default images;